//! Matrix family rules: shared detection types, unique `RuleMeta` per id.
//!
//! Generated by `scripts/gen_matrix_rules.py`. Re-run after catalog edits.

use vue_vet_core::{
  Confidence, FactKinds, FactRef, ReactiveBindingKind, ReactiveReadKind, Rule, RuleContext,
  RuleMeta, ScriptKind, Severity, TrackingScopeKind,
};

use crate::rules::support::{
  binding_path, effect_family, is_readonly_kind, unconditional_self_triggers, write_path,
};

struct BoundaryRule {
  meta: &'static RuleMeta,
  scope_kind: TrackingScopeKind,
  read_kind: ReactiveReadKind,
  scope_label: &'static str,
  reason: &'static str,
}

impl Rule for BoundaryRule {
  fn meta(&self) -> &'static RuleMeta {
    self.meta
  }

  fn fact_kinds(&self) -> FactKinds {
    FactKinds::TRACKING_SCOPE
  }

  fn run_on(&self, fact: FactRef<'_>, context: &mut RuleContext<'_>) {
    let FactRef::TrackingScope { scope, .. } = fact else {
      return;
    };
    if scope.kind != self.scope_kind {
      return;
    }
    for read in &scope.reads {
      if read.kind != self.read_kind {
        continue;
      }
      if self.read_kind == ReactiveReadKind::Conditional {
        let already = scope.reads.iter().any(|candidate| {
          candidate.kind == ReactiveReadKind::Unconditional
            && candidate.span.offset < read.span.offset
            && candidate.binding == read.binding
            && candidate.property == read.property
        });
        if already {
          continue;
        }
      }
      let path = binding_path(read);
      context.report(
        self.meta(),
        read.span.clone(),
        format!(
          "`{path}` is read {reason} inside {label}, so it is not a reliable dependency",
          reason = self.reason,
          label = self.scope_label
        ),
        Some(format!(
          "Read `{path}` synchronously in {label}, or use explicit `watch` sources.",
          label = self.scope_label
        )),
      );
    }
  }
}

macro_rules! boundary_rule {
  ($static_name:ident, $id:literal, $doc:literal, $scope:ident, $read:ident, $label:literal, $reason:literal) => {
    static $static_name: BoundaryRule = BoundaryRule {
      meta: &RuleMeta {
        id: $id,
        category: "reactivity",
        default_severity: Severity::Warning,
        confidence: Confidence::High,
        documentation: $doc,
      },
      scope_kind: TrackingScopeKind::$scope,
      read_kind: ReactiveReadKind::$read,
      scope_label: $label,
      reason: $reason,
    };
  };
}

boundary_rule!(
  B_NO_AFTER_AWAIT_DEPENDENCY_IN_COMPUTED,
  "vue-vet/reactivity/no-after-await-dependency-in-computed",
  "rules/reactivity/no-after-await-dependency-in-computed",
  Computed,
  AfterAwait,
  "computed",
  "after `await`"
);
boundary_rule!(
  B_NO_OUTSIDE_TRACKING_DEPENDENCY_IN_COMPUTED,
  "vue-vet/reactivity/no-outside-tracking-dependency-in-computed",
  "rules/reactivity/no-outside-tracking-dependency-in-computed",
  Computed,
  OutsideTracking,
  "computed",
  "outside synchronous tracking"
);
boundary_rule!(
  B_NO_CONDITIONAL_DEPENDENCY_IN_COMPUTED,
  "vue-vet/reactivity/no-conditional-dependency-in-computed",
  "rules/reactivity/no-conditional-dependency-in-computed",
  Computed,
  Conditional,
  "computed",
  "only after a control-flow guard"
);
boundary_rule!(
  B_NO_AFTER_AWAIT_DEPENDENCY_IN_WATCH_SOURCES,
  "vue-vet/reactivity/no-after-await-dependency-in-watch-sources",
  "rules/reactivity/no-after-await-dependency-in-watch-sources",
  WatchSources,
  AfterAwait,
  "watch sources",
  "after `await`"
);
boundary_rule!(
  B_NO_OUTSIDE_TRACKING_DEPENDENCY_IN_WATCH_SOURCES,
  "vue-vet/reactivity/no-outside-tracking-dependency-in-watch-sources",
  "rules/reactivity/no-outside-tracking-dependency-in-watch-sources",
  WatchSources,
  OutsideTracking,
  "watch sources",
  "outside synchronous tracking"
);
boundary_rule!(
  B_NO_CONDITIONAL_DEPENDENCY_IN_WATCH_SOURCES,
  "vue-vet/reactivity/no-conditional-dependency-in-watch-sources",
  "rules/reactivity/no-conditional-dependency-in-watch-sources",
  WatchSources,
  Conditional,
  "watch sources",
  "only after a control-flow guard"
);
boundary_rule!(
  B_NO_AFTER_AWAIT_DEPENDENCY_IN_EFFECT_SCOPE,
  "vue-vet/reactivity/no-after-await-dependency-in-effect-scope",
  "rules/reactivity/no-after-await-dependency-in-effect-scope",
  EffectScope,
  AfterAwait,
  "effectScope",
  "after `await`"
);
boundary_rule!(
  B_NO_OUTSIDE_TRACKING_DEPENDENCY_IN_EFFECT_SCOPE,
  "vue-vet/reactivity/no-outside-tracking-dependency-in-effect-scope",
  "rules/reactivity/no-outside-tracking-dependency-in-effect-scope",
  EffectScope,
  OutsideTracking,
  "effectScope",
  "outside synchronous tracking"
);
boundary_rule!(
  B_NO_CONDITIONAL_DEPENDENCY_IN_EFFECT_SCOPE,
  "vue-vet/reactivity/no-conditional-dependency-in-effect-scope",
  "rules/reactivity/no-conditional-dependency-in-effect-scope",
  EffectScope,
  Conditional,
  "effectScope",
  "only after a control-flow guard"
);

struct AfterAwaitCallRule {
  meta: &'static RuleMeta,
  callee: &'static str,
}

impl Rule for AfterAwaitCallRule {
  fn meta(&self) -> &'static RuleMeta {
    self.meta
  }

  fn run_once(&self, context: &mut RuleContext<'_>) {
    let mut findings = Vec::new();
    for block in &context.script().blocks {
      if block.kind != ScriptKind::Setup || block.top_level_await_ends.is_empty() {
        continue;
      }
      let Some(first_await_end) = block.top_level_await_ends.first().copied() else {
        continue;
      };
      for call in &block.calls {
        if call.callee != self.callee || call.span.offset < first_await_end {
          continue;
        }
        findings.push(call.span.clone());
      }
    }
    for span in findings {
      context.report(
        self.meta(),
        span,
        format!(
          "`{}` is registered after a top-level `await`, so it will not bind to this instance",
          self.callee
        ),
        Some(format!(
          "Move `{}` before the first top-level `await`, or register it in a synchronous setup path.",
          self.callee
        )),
      );
    }
  }
}

macro_rules! after_await_call_rule {
  ($static_name:ident, $id:literal, $doc:literal, $callee:literal) => {
    static $static_name: AfterAwaitCallRule = AfterAwaitCallRule {
      meta: &RuleMeta {
        id: $id,
        category: "correctness",
        default_severity: Severity::Warning,
        confidence: Confidence::High,
        documentation: $doc,
      },
      callee: $callee,
    };
  };
}

after_await_call_rule!(
  A_ON_MOUNTED,
  "vue-vet/correctness/no-on-mounted-after-await",
  "rules/correctness/no-on-mounted-after-await",
  "onMounted"
);
after_await_call_rule!(
  A_ON_BEFORE_MOUNT,
  "vue-vet/correctness/no-on-before-mount-after-await",
  "rules/correctness/no-on-before-mount-after-await",
  "onBeforeMount"
);
after_await_call_rule!(
  A_ON_UPDATED,
  "vue-vet/correctness/no-on-updated-after-await",
  "rules/correctness/no-on-updated-after-await",
  "onUpdated"
);
after_await_call_rule!(
  A_ON_BEFORE_UPDATE,
  "vue-vet/correctness/no-on-before-update-after-await",
  "rules/correctness/no-on-before-update-after-await",
  "onBeforeUpdate"
);
after_await_call_rule!(
  A_ON_UNMOUNTED,
  "vue-vet/correctness/no-on-unmounted-after-await",
  "rules/correctness/no-on-unmounted-after-await",
  "onUnmounted"
);
after_await_call_rule!(
  A_ON_BEFORE_UNMOUNT,
  "vue-vet/correctness/no-on-before-unmount-after-await",
  "rules/correctness/no-on-before-unmount-after-await",
  "onBeforeUnmount"
);
after_await_call_rule!(
  A_ON_ACTIVATED,
  "vue-vet/correctness/no-on-activated-after-await",
  "rules/correctness/no-on-activated-after-await",
  "onActivated"
);
after_await_call_rule!(
  A_ON_DEACTIVATED,
  "vue-vet/correctness/no-on-deactivated-after-await",
  "rules/correctness/no-on-deactivated-after-await",
  "onDeactivated"
);
after_await_call_rule!(
  A_ON_ERROR_CAPTURED,
  "vue-vet/correctness/no-on-error-captured-after-await",
  "rules/correctness/no-on-error-captured-after-await",
  "onErrorCaptured"
);
after_await_call_rule!(
  A_ON_RENDER_TRACKED,
  "vue-vet/correctness/no-on-render-tracked-after-await",
  "rules/correctness/no-on-render-tracked-after-await",
  "onRenderTracked"
);
after_await_call_rule!(
  A_ON_RENDER_TRIGGERED,
  "vue-vet/correctness/no-on-render-triggered-after-await",
  "rules/correctness/no-on-render-triggered-after-await",
  "onRenderTriggered"
);
after_await_call_rule!(
  A_ON_SERVER_PREFETCH,
  "vue-vet/correctness/no-on-server-prefetch-after-await",
  "rules/correctness/no-on-server-prefetch-after-await",
  "onServerPrefetch"
);
after_await_call_rule!(
  A_WATCH,
  "vue-vet/correctness/no-watch-after-await",
  "rules/correctness/no-watch-after-await",
  "watch"
);
after_await_call_rule!(
  A_WATCH_EFFECT,
  "vue-vet/correctness/no-watch-effect-after-await",
  "rules/correctness/no-watch-effect-after-await",
  "watchEffect"
);
after_await_call_rule!(
  A_WATCH_POST_EFFECT,
  "vue-vet/correctness/no-watch-post-effect-after-await",
  "rules/correctness/no-watch-post-effect-after-await",
  "watchPostEffect"
);
after_await_call_rule!(
  A_WATCH_SYNC_EFFECT,
  "vue-vet/correctness/no-watch-sync-effect-after-await",
  "rules/correctness/no-watch-sync-effect-after-await",
  "watchSyncEffect"
);
after_await_call_rule!(
  A_DEFINE_EXPOSE,
  "vue-vet/correctness/no-define-expose-after-await",
  "rules/correctness/no-define-expose-after-await",
  "defineExpose"
);
after_await_call_rule!(
  A_PROVIDE,
  "vue-vet/correctness/no-provide-after-await",
  "rules/correctness/no-provide-after-await",
  "provide"
);
after_await_call_rule!(
  A_INJECT,
  "vue-vet/correctness/no-inject-after-await",
  "rules/correctness/no-inject-after-await",
  "inject"
);
after_await_call_rule!(
  A_NEXT_TICK,
  "vue-vet/correctness/no-next-tick-after-await",
  "rules/correctness/no-next-tick-after-await",
  "nextTick"
);
after_await_call_rule!(
  A_EFFECT_SCOPE,
  "vue-vet/correctness/no-effect-scope-after-await",
  "rules/correctness/no-effect-scope-after-await",
  "effectScope"
);
after_await_call_rule!(
  A_GET_CURRENT_INSTANCE,
  "vue-vet/correctness/no-get-current-instance-after-await",
  "rules/correctness/no-get-current-instance-after-await",
  "getCurrentInstance"
);
after_await_call_rule!(
  A_USE_ATTRS,
  "vue-vet/correctness/no-use-attrs-after-await",
  "rules/correctness/no-use-attrs-after-await",
  "useAttrs"
);
after_await_call_rule!(
  A_USE_SLOTS,
  "vue-vet/correctness/no-use-slots-after-await",
  "rules/correctness/no-use-slots-after-await",
  "useSlots"
);
after_await_call_rule!(
  A_USE_CSS_MODULE,
  "vue-vet/correctness/no-use-css-module-after-await",
  "rules/correctness/no-use-css-module-after-await",
  "useCssModule"
);
after_await_call_rule!(
  A_USE_CSS_VARS,
  "vue-vet/correctness/no-use-css-vars-after-await",
  "rules/correctness/no-use-css-vars-after-await",
  "useCssVars"
);
after_await_call_rule!(
  A_WITH_DEFAULTS,
  "vue-vet/correctness/no-with-defaults-after-await",
  "rules/correctness/no-with-defaults-after-await",
  "withDefaults"
);

enum PathologyKind {
  SelfTrigger,
  SideEffectsInComputed,
  WriteWithoutRead,
  NoDependency,
  PreferWatchSingle,
  AssignOnlyConditional,
  DisposeRead,
  EmptyWatchSources,
}

struct PathologyRule {
  meta: &'static RuleMeta,
  kind: PathologyKind,
  scope_filter: TrackingScopeKind,
  effect_family_only: bool,
}

impl Rule for PathologyRule {
  fn meta(&self) -> &'static RuleMeta {
    self.meta
  }

  fn fact_kinds(&self) -> FactKinds {
    FactKinds::TRACKING_SCOPE
  }

  fn run_on(&self, fact: FactRef<'_>, context: &mut RuleContext<'_>) {
    let FactRef::TrackingScope { scope, .. } = fact else {
      return;
    };
    let matches_scope = if self.effect_family_only {
      effect_family(scope.kind)
    } else {
      scope.kind == self.scope_filter
    };
    if !matches_scope {
      return;
    }
    match self.kind {
      PathologyKind::SelfTrigger => {
        for read in unconditional_self_triggers(scope) {
          let path = binding_path(read);
          context.report(
            self.meta(),
            read.span.clone(),
            format!(
              "`{path}` is read and written in the same tracking scope, which can self-trigger"
            ),
            Some(
              "Avoid writing a dependency you also read, or split read/write across scopes.".into(),
            ),
          );
        }
      }
      PathologyKind::SideEffectsInComputed => {
        for write in &scope.writes {
          context.report(
            self.meta(),
            write.span.clone(),
            format!("computed getter writes `{}`, which is a side effect", write_path(write)),
            Some("Keep computed getters pure; move writes into `watch` / event handlers.".into()),
          );
        }
      }
      PathologyKind::WriteWithoutRead => {
        if scope.writes.is_empty() || !scope.reads.is_empty() {
          return;
        }
        context.report(
          self.meta(),
          scope.span.clone(),
          format!("`{}` writes reactive state but reads no reactive dependency", scope.callee),
          Some("Effects without reactive reads never re-run; use a plain function or explicit trigger.".into()),
        );
      }
      PathologyKind::NoDependency => {
        if !scope.reads.is_empty() {
          return;
        }
        let (message, help) = if scope.uncertain_accesses.is_empty() {
          (
            "`computed` does not read any reactive dependency".into(),
            Some("Return a plain value, or read reactive state inside the getter.".into()),
          )
        } else {
          let maybe = scope
            .uncertain_accesses
            .iter()
            .map(|name| format!("`{name}`"))
            .collect::<Vec<_>>()
            .join(", ");
          (
            format!(
              "`computed` does not read any known reactive dependency (maybe: {maybe})"
            ),
            Some(
              "Analyzed `.value` / `unref` / `toValue` on names that could not be classified as reactive bindings. Return a plain value, or ensure the dependency is a known ref/reactive source.".into(),
            ),
          )
        };
        context.report(self.meta(), scope.span.clone(), message, help);
      }
      PathologyKind::PreferWatchSingle => {
        if !scope.assignment_only {
          return;
        }
        if scope.reads.iter().any(|read| read.kind != ReactiveReadKind::Unconditional) {
          return;
        }
        let unconditional: Vec<_> = scope.reads.iter().collect();
        if unconditional.len() != 1 {
          return;
        }
        let Some(read) = unconditional.first() else {
          return;
        };
        let path = binding_path(read);
        context.report(
          self.meta(),
          scope.span.clone(),
          format!(
            "`{}` only tracks `{path}`; prefer `watch` with an explicit source",
            scope.callee
          ),
          Some(format!(
            "Use `watch(() => {path}, …)` (or `watch({path}, …)` for a ref) for a single source."
          )),
        );
      }
      PathologyKind::AssignOnlyConditional => {
        if !scope.assignment_only {
          return;
        }
        if !scope.reads.iter().any(|read| read.kind == ReactiveReadKind::Conditional) {
          return;
        }
        context.report(
          self.meta(),
          scope.span.clone(),
          format!(
            "`{}` is assignment-only but tracks at least one conditional dependency",
            scope.callee
          ),
          Some(
            "Use explicit `watch` sources for every value that must invalidate the sync.".into(),
          ),
        );
      }
      PathologyKind::DisposeRead => {
        for read in &scope.reads {
          let path = binding_path(read);
          context.report(
            self.meta(),
            read.span.clone(),
            format!("`{path}` is read in `onScopeDispose`, which is not a tracking scope"),
            Some(
              "Capture values before dispose, or clean up without relying on reactive tracking."
                .into(),
            ),
          );
        }
      }
      PathologyKind::EmptyWatchSources => {
        if !scope.reads.is_empty() {
          return;
        }
        context.report(
          self.meta(),
          scope.span.clone(),
          "`watch` sources do not read any reactive dependency".into(),
          Some("Pass a ref, a getter, or an array of sources that read reactive state.".into()),
        );
      }
    }
  }
}

macro_rules! pathology_rule {
  ($static_name:ident, $id:literal, $doc:literal, $kind:ident, $scope:ident, $effect_family:expr) => {
    static $static_name: PathologyRule = PathologyRule {
      meta: &RuleMeta {
        id: $id,
        category: "reactivity",
        default_severity: Severity::Warning,
        confidence: Confidence::High,
        documentation: $doc,
      },
      kind: PathologyKind::$kind,
      scope_filter: TrackingScopeKind::$scope,
      effect_family_only: $effect_family,
    };
  };
}

pathology_rule!(
  P_NO_SELF_TRIGGER_IN_WATCH_EFFECT,
  "vue-vet/reactivity/no-self-trigger-in-watch-effect",
  "rules/reactivity/no-self-trigger-in-watch-effect",
  SelfTrigger,
  WatchEffect,
  false
);
pathology_rule!(
  P_NO_SELF_TRIGGER_IN_WATCH_POST_EFFECT,
  "vue-vet/reactivity/no-self-trigger-in-watch-post-effect",
  "rules/reactivity/no-self-trigger-in-watch-post-effect",
  SelfTrigger,
  WatchPostEffect,
  false
);
pathology_rule!(
  P_NO_SELF_TRIGGER_IN_WATCH_SYNC_EFFECT,
  "vue-vet/reactivity/no-self-trigger-in-watch-sync-effect",
  "rules/reactivity/no-self-trigger-in-watch-sync-effect",
  SelfTrigger,
  WatchSyncEffect,
  false
);
pathology_rule!(
  P_NO_COMPUTED_SELF_TRIGGER,
  "vue-vet/reactivity/no-computed-self-trigger",
  "rules/reactivity/no-computed-self-trigger",
  SelfTrigger,
  Computed,
  false
);
pathology_rule!(
  P_NO_SIDE_EFFECTS_IN_COMPUTED,
  "vue-vet/reactivity/no-side-effects-in-computed",
  "rules/reactivity/no-side-effects-in-computed",
  SideEffectsInComputed,
  Computed,
  false
);
pathology_rule!(
  P_NO_EFFECT_WRITE_WITHOUT_READ,
  "vue-vet/reactivity/no-effect-write-without-read",
  "rules/reactivity/no-effect-write-without-read",
  WriteWithoutRead,
  WatchEffect,
  true
);
pathology_rule!(
  P_NO_COMPUTED_WITHOUT_DEPENDENCY,
  "vue-vet/reactivity/no-computed-without-dependency",
  "rules/reactivity/no-computed-without-dependency",
  NoDependency,
  Computed,
  false
);
pathology_rule!(
  P_PREFER_WATCH_OVER_EFFECT_FOR_SINGLE_SOURCE,
  "vue-vet/reactivity/prefer-watch-over-effect-for-single-source",
  "rules/reactivity/prefer-watch-over-effect-for-single-source",
  PreferWatchSingle,
  WatchEffect,
  true
);
pathology_rule!(
  P_NO_ASSIGNMENT_ONLY_EFFECT_WITH_CONDITIONAL_READ,
  "vue-vet/reactivity/no-assignment-only-effect-with-conditional-read",
  "rules/reactivity/no-assignment-only-effect-with-conditional-read",
  AssignOnlyConditional,
  WatchEffect,
  true
);
pathology_rule!(
  P_NO_ON_SCOPE_DISPOSE_REACTIVE_READ,
  "vue-vet/reactivity/no-on-scope-dispose-reactive-read",
  "rules/reactivity/no-on-scope-dispose-reactive-read",
  DisposeRead,
  OnScopeDispose,
  false
);
pathology_rule!(
  P_NO_EMPTY_WATCH_SOURCES,
  "vue-vet/reactivity/no-empty-watch-sources",
  "rules/reactivity/no-empty-watch-sources",
  EmptyWatchSources,
  WatchSources,
  false
);

struct WatchCallbackTrackingRule;

impl Rule for WatchCallbackTrackingRule {
  fn meta(&self) -> &'static RuleMeta {
    &RuleMeta {
      id: "vue-vet/reactivity/no-watch-callback-as-tracking-scope",
      category: "reactivity",
      default_severity: Severity::Warning,
      confidence: Confidence::High,
      documentation: "rules/reactivity/no-watch-callback-as-tracking-scope",
    }
  }

  fn run_once(&self, context: &mut RuleContext<'_>) {
    let mut findings = Vec::new();
    for block in &context.script().blocks {
      let scopes = &block.reactivity_graph.scopes;
      let mut index = 0;
      while index + 1 < scopes.len() {
        let Some(sources) = scopes.get(index) else {
          break;
        };
        let Some(callback) = scopes.get(index + 1) else {
          break;
        };
        if sources.kind == TrackingScopeKind::WatchSources
          && callback.kind == TrackingScopeKind::WatchCallback
          && sources.reads.is_empty()
          && !callback.reads.is_empty()
        {
          findings.push(callback.span.clone());
        }
        index += 1;
      }
    }
    for span in findings {
      context.report(
        self.meta(),
        span,
        "reactive reads in a `watch` callback are not tracked for invalidation".into(),
        Some(
          "List dependencies in the `watch` source argument; the callback is a side-effect sink."
            .into(),
        ),
      );
    }
  }
}

static P_WATCH_CALLBACK_TRACKING: WatchCallbackTrackingRule = WatchCallbackTrackingRule;

struct DestructureSourceRule {
  meta: &'static RuleMeta,
  source: &'static str,
  message: &'static str,
  help: &'static str,
  pinia_store: bool,
}

impl Rule for DestructureSourceRule {
  fn meta(&self) -> &'static RuleMeta {
    self.meta
  }

  fn fact_kinds(&self) -> FactKinds {
    FactKinds::SCRIPT_DESTRUCTURE
  }

  fn run_on(&self, fact: FactRef<'_>, context: &mut RuleContext<'_>) {
    let FactRef::ScriptDestructure { destructure, .. } = fact else {
      return;
    };
    let matched = if self.pinia_store {
      let name = destructure.source_call.as_str();
      name.starts_with("use") && name.ends_with("Store")
    } else {
      destructure.source_call == self.source
    };
    if !matched {
      return;
    }
    context.report(
      self.meta(),
      destructure.span.clone(),
      self.message.into(),
      Some(self.help.into()),
    );
  }
}

macro_rules! destructure_rule {
  ($static_name:ident, $id:literal, $doc:literal, $source:literal, $message:literal, $help:literal, $pinia:expr) => {
    static $static_name: DestructureSourceRule = DestructureSourceRule {
      meta: &RuleMeta {
        id: $id,
        category: "reactivity",
        default_severity: Severity::Warning,
        confidence: Confidence::High,
        documentation: $doc,
      },
      source: $source,
      message: $message,
      help: $help,
      pinia_store: $pinia,
    };
  };
}

destructure_rule!(
  I_REACTIVE_DESTRUCTURE,
  "vue-vet/reactivity/no-reactive-destructure",
  "rules/reactivity/no-reactive-destructure",
  "reactive",
  "destructuring `reactive()` loses reactivity for the pulled fields",
  "Keep the reactive object, or use `toRefs` / `toRef`.",
  false
);
destructure_rule!(
  I_SHALLOW_REACTIVE_DESTRUCTURE,
  "vue-vet/reactivity/no-shallow-reactive-destructure",
  "rules/reactivity/no-shallow-reactive-destructure",
  "shallowReactive",
  "destructuring `shallowReactive()` loses reactivity for the pulled fields",
  "Keep the shallowReactive object, or use `toRefs` / `toRef`.",
  false
);
destructure_rule!(
  I_PREFER_STORE_TO_REFS,
  "vue-vet/reactivity/prefer-store-to-refs",
  "rules/reactivity/prefer-store-to-refs",
  "",
  "destructuring a Pinia store loses reactivity for state fields",
  "Use `storeToRefs(store)` for state/getters, and keep actions on the store object.",
  true
);
destructure_rule!(
  I_ROUTE_DESTRUCTURE,
  "vue-vet/reactivity/no-route-destructure",
  "rules/reactivity/no-route-destructure",
  "useRoute",
  "destructuring `useRoute()` loses reactivity",
  "Keep the route object or read `route.params` / `route.query` through it.",
  false
);
destructure_rule!(
  I_ROUTER_DESTRUCTURE,
  "vue-vet/reactivity/no-router-destructure",
  "rules/reactivity/no-router-destructure",
  "useRouter",
  "destructuring `useRouter()` is usually unnecessary and can hide API misuse",
  "Keep the router instance and call methods on it.",
  false
);

struct RefOperandRule {
  meta: &'static RuleMeta,
  kinds: &'static [ReactiveBindingKind],
  label: &'static str,
}

impl Rule for RefOperandRule {
  fn meta(&self) -> &'static RuleMeta {
    self.meta
  }

  fn fact_kinds(&self) -> FactKinds {
    FactKinds::SCRIPT_OPERAND
  }

  fn run_on(&self, fact: FactRef<'_>, context: &mut RuleContext<'_>) {
    let FactRef::ScriptOperand { block_kind, operand } = fact else {
      return;
    };
    let Some(block) = context.script().blocks.iter().find(|block| block.kind == block_kind) else {
      return;
    };
    let Some(binding) =
      block.reactivity_graph.bindings.iter().find(|binding| binding.name == operand.name)
    else {
      return;
    };
    if !self.kinds.contains(&binding.kind) {
      return;
    }
    context.report(
      self.meta(),
      operand.span.clone(),
      format!(
        "`{}` is a {} object used as an operand; unwrap with `.value` (or `toValue`)",
        operand.name, self.label
      ),
      Some(format!(
        "Use `{}.value` (or `toValue({})`) when reading the inner value.",
        operand.name, operand.name
      )),
    );
  }
}

macro_rules! ref_operand_rule {
  ($static_name:ident, $id:literal, $doc:literal, $label:literal, [$($kind:ident),+]) => {
    static $static_name: RefOperandRule = RefOperandRule {
      meta: &RuleMeta {
        id: $id,
        category: "reactivity",
        default_severity: Severity::Warning,
        confidence: Confidence::High,
        documentation: $doc,
      },
      kinds: &[$(ReactiveBindingKind::$kind),+],
      label: $label,
    };
  };
}

ref_operand_rule!(
  I_REF_AS_OPERAND,
  "vue-vet/reactivity/no-ref-as-operand",
  "rules/reactivity/no-ref-as-operand",
  "ref",
  [Ref, ShallowRef, CustomRef, ToRef, TemplateRef]
);
ref_operand_rule!(
  I_MODEL_REF_AS_OPERAND,
  "vue-vet/reactivity/no-model-ref-as-operand",
  "rules/reactivity/no-model-ref-as-operand",
  "defineModel ref",
  [ModelRef]
);
ref_operand_rule!(
  I_COMPUTED_AS_OPERAND,
  "vue-vet/reactivity/no-computed-as-operand",
  "rules/reactivity/no-computed-as-operand",
  "computed ref",
  [Computed]
);

struct ReadonlyMutationRule;

impl Rule for ReadonlyMutationRule {
  fn meta(&self) -> &'static RuleMeta {
    &RuleMeta {
      id: "vue-vet/reactivity/no-readonly-mutation",
      category: "reactivity",
      default_severity: Severity::Warning,
      confidence: Confidence::High,
      documentation: "rules/reactivity/no-readonly-mutation",
    }
  }

  fn fact_kinds(&self) -> FactKinds {
    FactKinds::SCRIPT_MEMBER_WRITE
  }

  fn run_on(&self, fact: FactRef<'_>, context: &mut RuleContext<'_>) {
    let FactRef::ScriptMemberWrite { block_kind, write } = fact else {
      return;
    };
    let Some(block) = context.script().blocks.iter().find(|block| block.kind == block_kind) else {
      return;
    };
    let Some(binding) =
      block.reactivity_graph.bindings.iter().find(|binding| binding.name == write.object)
    else {
      return;
    };
    if !is_readonly_kind(binding.kind) {
      return;
    }
    context.report(
      self.meta(),
      write.span.clone(),
      format!("`{}` is readonly and should not be mutated", write.object),
      Some("Mutate the source reactive state instead of a readonly projection.".into()),
    );
  }
}

static I_READONLY_MUTATION: ReadonlyMutationRule = ReadonlyMutationRule;

// Reserved: register when top-level vs nested template-ref reads are distinguishable.
#[expect(dead_code)]
struct TemplateRefSetupReadRule;
#[expect(dead_code)]
static I_TEMPLATE_REF_SETUP_READ: TemplateRefSetupReadRule = TemplateRefSetupReadRule;

#[must_use]
pub fn matrix_rules() -> Vec<&'static dyn Rule> {
  vec![
    &B_NO_AFTER_AWAIT_DEPENDENCY_IN_COMPUTED,
    &B_NO_OUTSIDE_TRACKING_DEPENDENCY_IN_COMPUTED,
    &B_NO_CONDITIONAL_DEPENDENCY_IN_COMPUTED,
    &B_NO_AFTER_AWAIT_DEPENDENCY_IN_WATCH_SOURCES,
    &B_NO_OUTSIDE_TRACKING_DEPENDENCY_IN_WATCH_SOURCES,
    &B_NO_CONDITIONAL_DEPENDENCY_IN_WATCH_SOURCES,
    &B_NO_AFTER_AWAIT_DEPENDENCY_IN_EFFECT_SCOPE,
    &B_NO_OUTSIDE_TRACKING_DEPENDENCY_IN_EFFECT_SCOPE,
    &B_NO_CONDITIONAL_DEPENDENCY_IN_EFFECT_SCOPE,
    &A_ON_MOUNTED,
    &A_ON_BEFORE_MOUNT,
    &A_ON_UPDATED,
    &A_ON_BEFORE_UPDATE,
    &A_ON_UNMOUNTED,
    &A_ON_BEFORE_UNMOUNT,
    &A_ON_ACTIVATED,
    &A_ON_DEACTIVATED,
    &A_ON_ERROR_CAPTURED,
    &A_ON_RENDER_TRACKED,
    &A_ON_RENDER_TRIGGERED,
    &A_ON_SERVER_PREFETCH,
    &A_WATCH,
    &A_WATCH_EFFECT,
    &A_WATCH_POST_EFFECT,
    &A_WATCH_SYNC_EFFECT,
    &A_DEFINE_EXPOSE,
    &A_PROVIDE,
    &A_INJECT,
    &A_NEXT_TICK,
    &A_EFFECT_SCOPE,
    &A_GET_CURRENT_INSTANCE,
    &A_USE_ATTRS,
    &A_USE_SLOTS,
    &A_USE_CSS_MODULE,
    &A_USE_CSS_VARS,
    &A_WITH_DEFAULTS,
    &P_NO_SELF_TRIGGER_IN_WATCH_EFFECT,
    &P_NO_SELF_TRIGGER_IN_WATCH_POST_EFFECT,
    &P_NO_SELF_TRIGGER_IN_WATCH_SYNC_EFFECT,
    &P_NO_COMPUTED_SELF_TRIGGER,
    &P_NO_SIDE_EFFECTS_IN_COMPUTED,
    &P_NO_EFFECT_WRITE_WITHOUT_READ,
    &P_NO_COMPUTED_WITHOUT_DEPENDENCY,
    &P_PREFER_WATCH_OVER_EFFECT_FOR_SINGLE_SOURCE,
    &P_NO_ASSIGNMENT_ONLY_EFFECT_WITH_CONDITIONAL_READ,
    &P_NO_ON_SCOPE_DISPOSE_REACTIVE_READ,
    &P_NO_EMPTY_WATCH_SOURCES,
    &P_WATCH_CALLBACK_TRACKING,
    &I_REACTIVE_DESTRUCTURE,
    &I_SHALLOW_REACTIVE_DESTRUCTURE,
    &I_PREFER_STORE_TO_REFS,
    &I_ROUTE_DESTRUCTURE,
    &I_ROUTER_DESTRUCTURE,
    &I_REF_AS_OPERAND,
    &I_MODEL_REF_AS_OPERAND,
    &I_COMPUTED_AS_OPERAND,
    &I_READONLY_MUTATION,
  ]
}
