#!/usr/bin/env python3
"""Generate crates/vue_vet_rules/src/rules/matrix/mod.rs catalog."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "crates/vue_vet_rules/src/rules/matrix/mod.rs"


def main() -> None:
  boundary: list[tuple[str, str, str, str, str, str]] = []
  scopes = [
    ("computed", "Computed", "computed"),
    ("watch-sources", "WatchSources", "watch sources"),
    ("effect-scope", "EffectScope", "effectScope"),
  ]
  boundaries = [
    ("after-await", "AfterAwait", "after `await`"),
    ("outside-tracking", "OutsideTracking", "outside synchronous tracking"),
    ("conditional", "Conditional", "only after a control-flow guard"),
  ]
  for s_slug, s_kind, s_label in scopes:
    for b_slug, b_kind, b_msg in boundaries:
      slug = f"no-{b_slug}-dependency-in-{s_slug}"
      rid = f"vue-vet/reactivity/{slug}"
      boundary.append((rid, s_kind, b_kind, s_label, b_msg, slug))

  await_calls: list[tuple[str, str, str]] = []
  hooks = [
    ("onMounted", "on-mounted"),
    ("onBeforeMount", "on-before-mount"),
    ("onUpdated", "on-updated"),
    ("onBeforeUpdate", "on-before-update"),
    ("onUnmounted", "on-unmounted"),
    ("onBeforeUnmount", "on-before-unmount"),
    ("onActivated", "on-activated"),
    ("onDeactivated", "on-deactivated"),
    ("onErrorCaptured", "on-error-captured"),
    ("onRenderTracked", "on-render-tracked"),
    ("onRenderTriggered", "on-render-triggered"),
    ("onServerPrefetch", "on-server-prefetch"),
    ("watch", "watch"),
    ("watchEffect", "watch-effect"),
    ("watchPostEffect", "watch-post-effect"),
    ("watchSyncEffect", "watch-sync-effect"),
    ("defineExpose", "define-expose"),
    ("provide", "provide"),
    ("inject", "inject"),
    ("nextTick", "next-tick"),
    ("effectScope", "effect-scope"),
    ("getCurrentInstance", "get-current-instance"),
    ("useAttrs", "use-attrs"),
    ("useSlots", "use-slots"),
    ("useCssModule", "use-css-module"),
    ("useCssVars", "use-css-vars"),
    ("withDefaults", "with-defaults"),
  ]
  for callee, slug in hooks:
    await_calls.append((f"vue-vet/correctness/no-{slug}-after-await", callee, slug))

  # Note: do not matrix WatchCallback × OutsideTracking — callback reads are
  # expected side-effect sinks (covered by no-watch-callback-as-tracking-scope).

  pathology = [
    ("vue-vet/reactivity/no-self-trigger-in-watch-effect", "SelfTrigger", "WatchEffect", False),
    ("vue-vet/reactivity/no-self-trigger-in-watch-post-effect", "SelfTrigger", "WatchPostEffect", False),
    ("vue-vet/reactivity/no-self-trigger-in-watch-sync-effect", "SelfTrigger", "WatchSyncEffect", False),
    ("vue-vet/reactivity/no-computed-self-trigger", "SelfTrigger", "Computed", False),
    ("vue-vet/reactivity/no-side-effects-in-computed", "SideEffectsInComputed", "Computed", False),
    ("vue-vet/reactivity/no-effect-write-without-read", "WriteWithoutRead", "WatchEffect", True),
    ("vue-vet/reactivity/no-computed-without-dependency", "NoDependency", "Computed", False),
    ("vue-vet/reactivity/prefer-watch-over-effect-for-single-source", "PreferWatchSingle", "WatchEffect", True),
    (
      "vue-vet/reactivity/no-assignment-only-effect-with-conditional-read",
      "AssignOnlyConditional",
      "WatchEffect",
      True,
    ),
    ("vue-vet/reactivity/no-on-scope-dispose-reactive-read", "DisposeRead", "OnScopeDispose", False),
    ("vue-vet/reactivity/no-empty-watch-sources", "EmptyWatchSources", "WatchSources", False),
  ]

  parts: list[str] = []
  parts.append(
    """//! Matrix family rules: shared detection types, unique RuleMeta per id.
//!
//! Generated by `scripts/gen_matrix_rules.py`. Re-run after catalog edits.

use vue_vet_core::{
  Confidence, FactKinds, FactRef, ReactiveBindingKind, ReactiveReadKind, Rule, RuleContext, RuleMeta,
  ScriptKind, Severity, TrackingScopeKind,
};

use crate::rules::support::{
  binding_path, effect_family, is_readonly_kind, unconditional_self_triggers, write_path,
};

struct BoundaryRule {
  meta: &'static RuleMeta,
  scope_kind: TrackingScopeKind,
  read_kind: ReactiveReadKind,
  scope_label: &'static str,
  reason: &'static str,
}

impl Rule for BoundaryRule {
  fn meta(&self) -> &'static RuleMeta {
    self.meta
  }

  fn fact_kinds(&self) -> FactKinds {
    FactKinds::TRACKING_SCOPE
  }

  fn run_on(&self, fact: FactRef<'_>, context: &mut RuleContext<'_>) {
    let FactRef::TrackingScope { scope, .. } = fact else {
      return;
    };
    if scope.kind != self.scope_kind {
      return;
    }
    for read in &scope.reads {
      if read.kind != self.read_kind {
        continue;
      }
      if self.read_kind == ReactiveReadKind::Conditional {
        let already = scope.reads.iter().any(|candidate| {
          candidate.kind == ReactiveReadKind::Unconditional
            && candidate.span.offset < read.span.offset
            && candidate.binding == read.binding
            && candidate.property == read.property
        });
        if already {
          continue;
        }
      }
      let path = binding_path(read);
      context.report(
        self.meta(),
        read.span.clone(),
        format!(
          "`{path}` is read {reason} inside {label}, so it is not a reliable dependency",
          reason = self.reason,
          label = self.scope_label
        ),
        Some(format!(
          "Read `{path}` synchronously in {label}, or use explicit `watch` sources.",
          label = self.scope_label
        )),
      );
    }
  }
}

macro_rules! boundary_rule {
  ($static_name:ident, $id:literal, $doc:literal, $scope:ident, $read:ident, $label:literal, $reason:literal) => {
    static $static_name: BoundaryRule = BoundaryRule {
      meta: &RuleMeta {
        id: $id,
        category: "reactivity",
        default_severity: Severity::Warning,
        confidence: Confidence::High,
        documentation: $doc,
      },
      scope_kind: TrackingScopeKind::$scope,
      read_kind: ReactiveReadKind::$read,
      scope_label: $label,
      reason: $reason,
    };
  };
}
"""
  )

  b_statics: list[str] = []
  for rid, s_kind, b_kind, s_label, b_msg, slug in boundary:
    static_name = "B_" + slug.replace("-", "_").upper()
    b_statics.append(static_name)
    parts.append(
      f'boundary_rule!({static_name}, "{rid}", "rules/reactivity/{slug}", {s_kind}, {b_kind}, "{s_label}", "{b_msg}");'
    )

  parts.append(
    """
struct AfterAwaitCallRule {
  meta: &'static RuleMeta,
  callee: &'static str,
}

impl Rule for AfterAwaitCallRule {
  fn meta(&self) -> &'static RuleMeta {
    self.meta
  }

  fn run_once(&self, context: &mut RuleContext<'_>) {
    let mut findings = Vec::new();
    for block in &context.script().blocks {
      if block.kind != ScriptKind::Setup || block.top_level_await_ends.is_empty() {
        continue;
      }
      let Some(first_await_end) = block.top_level_await_ends.first().copied() else {
        continue;
      };
      for call in &block.calls {
        if call.callee != self.callee || call.span.offset < first_await_end {
          continue;
        }
        findings.push(call.span.clone());
      }
    }
    for span in findings {
      context.report(
        self.meta(),
        span,
        format!(
          "`{}` is registered after a top-level `await`, so it will not bind to this instance",
          self.callee
        ),
        Some(format!(
          "Move `{}` before the first top-level `await`, or register it in a synchronous setup path.",
          self.callee
        )),
      );
    }
  }
}

macro_rules! after_await_call_rule {
  ($static_name:ident, $id:literal, $doc:literal, $callee:literal) => {
    static $static_name: AfterAwaitCallRule = AfterAwaitCallRule {
      meta: &RuleMeta {
        id: $id,
        category: "correctness",
        default_severity: Severity::Warning,
        confidence: Confidence::High,
        documentation: $doc,
      },
      callee: $callee,
    };
  };
}
"""
  )

  a_statics: list[str] = []
  for rid, callee, slug in await_calls:
    static_name = "A_" + slug.replace("-", "_").upper()
    a_statics.append(static_name)
    parts.append(
      f'after_await_call_rule!({static_name}, "{rid}", "rules/correctness/no-{slug}-after-await", "{callee}");'
    )

  parts.append(
    """
enum PathologyKind {
  SelfTrigger,
  SideEffectsInComputed,
  WriteWithoutRead,
  NoDependency,
  PreferWatchSingle,
  AssignOnlyConditional,
  DisposeRead,
  EmptyWatchSources,
}

struct PathologyRule {
  meta: &'static RuleMeta,
  kind: PathologyKind,
  scope_filter: TrackingScopeKind,
  effect_family_only: bool,
}

impl Rule for PathologyRule {
  fn meta(&self) -> &'static RuleMeta {
    self.meta
  }

  fn fact_kinds(&self) -> FactKinds {
    FactKinds::TRACKING_SCOPE
  }

  fn run_on(&self, fact: FactRef<'_>, context: &mut RuleContext<'_>) {
    let FactRef::TrackingScope { scope, .. } = fact else {
      return;
    };
    let matches_scope = if self.effect_family_only {
      effect_family(scope.kind)
    } else {
      scope.kind == self.scope_filter
    };
    if !matches_scope {
      return;
    }
    match self.kind {
      PathologyKind::SelfTrigger => {
        for read in unconditional_self_triggers(scope) {
          let path = binding_path(read);
          context.report(
            self.meta(),
            read.span.clone(),
            format!("`{path}` is read and written in the same tracking scope, which can self-trigger"),
            Some("Avoid writing a dependency you also read, or split read/write across scopes.".into()),
          );
        }
      }
      PathologyKind::SideEffectsInComputed => {
        for write in &scope.writes {
          context.report(
            self.meta(),
            write.span.clone(),
            format!("computed getter writes `{}`, which is a side effect", write_path(write)),
            Some("Keep computed getters pure; move writes into `watch` / event handlers.".into()),
          );
        }
      }
      PathologyKind::WriteWithoutRead => {
        if scope.writes.is_empty() || !scope.reads.is_empty() {
          return;
        }
        context.report(
          self.meta(),
          scope.span.clone(),
          format!("`{}` writes reactive state but reads no reactive dependency", scope.callee),
          Some("Effects without reactive reads never re-run; use a plain function or explicit trigger.".into()),
        );
      }
      PathologyKind::NoDependency => {
        if !scope.reads.is_empty() {
          return;
        }
        context.report(
          self.meta(),
          scope.span.clone(),
          "`computed` does not read any reactive dependency".into(),
          Some("Return a plain value, or read reactive state inside the getter.".into()),
        );
      }
      PathologyKind::PreferWatchSingle => {
        if !scope.assignment_only {
          return;
        }
        if scope.reads.iter().any(|read| read.kind != ReactiveReadKind::Unconditional) {
          return;
        }
        let unconditional: Vec<_> = scope.reads.iter().collect();
        if unconditional.len() != 1 {
          return;
        }
        let Some(read) = unconditional.first() else {
          return;
        };
        let path = binding_path(read);
        context.report(
          self.meta(),
          scope.span.clone(),
          format!("`{}` only tracks `{path}`; prefer `watch` with an explicit source", scope.callee),
          Some(format!(
            "Use `watch(() => {path}, …)` (or `watch({path}, …)` for a ref) for a single source."
          )),
        );
      }
      PathologyKind::AssignOnlyConditional => {
        if !scope.assignment_only {
          return;
        }
        if !scope.reads.iter().any(|read| read.kind == ReactiveReadKind::Conditional) {
          return;
        }
        context.report(
          self.meta(),
          scope.span.clone(),
          format!(
            "`{}` is assignment-only but tracks at least one conditional dependency",
            scope.callee
          ),
          Some("Use explicit `watch` sources for every value that must invalidate the sync.".into()),
        );
      }
      PathologyKind::DisposeRead => {
        for read in &scope.reads {
          let path = binding_path(read);
          context.report(
            self.meta(),
            read.span.clone(),
            format!("`{path}` is read in `onScopeDispose`, which is not a tracking scope"),
            Some("Capture values before dispose, or clean up without relying on reactive tracking.".into()),
          );
        }
      }
      PathologyKind::EmptyWatchSources => {
        if !scope.reads.is_empty() {
          return;
        }
        context.report(
          self.meta(),
          scope.span.clone(),
          "`watch` sources do not read any reactive dependency".into(),
          Some("Pass a ref, a getter, or an array of sources that read reactive state.".into()),
        );
      }
    }
  }
}

macro_rules! pathology_rule {
  ($static_name:ident, $id:literal, $doc:literal, $kind:ident, $scope:ident, $effect_family:expr) => {
    static $static_name: PathologyRule = PathologyRule {
      meta: &RuleMeta {
        id: $id,
        category: "reactivity",
        default_severity: Severity::Warning,
        confidence: Confidence::High,
        documentation: $doc,
      },
      kind: PathologyKind::$kind,
      scope_filter: TrackingScopeKind::$scope,
      effect_family_only: $effect_family,
    };
  };
}
"""
  )

  p_statics: list[str] = []
  for rid, kind, scope, effect_family in pathology:
    slug = rid.rsplit("/", 1)[-1]
    static_name = "P_" + slug.replace("-", "_").upper()
    p_statics.append(static_name)
    parts.append(
      f'pathology_rule!({static_name}, "{rid}", "rules/reactivity/{slug}", {kind}, {scope}, {"true" if effect_family else "false"});'
    )

  parts.append(
    """
struct WatchCallbackTrackingRule;

impl Rule for WatchCallbackTrackingRule {
  fn meta(&self) -> &'static RuleMeta {
    &RuleMeta {
      id: "vue-vet/reactivity/no-watch-callback-as-tracking-scope",
      category: "reactivity",
      default_severity: Severity::Warning,
      confidence: Confidence::High,
      documentation: "rules/reactivity/no-watch-callback-as-tracking-scope",
    }
  }

  fn run_once(&self, context: &mut RuleContext<'_>) {
    let mut findings = Vec::new();
    for block in &context.script().blocks {
      let scopes = &block.reactivity_graph.scopes;
      let mut index = 0;
      while index + 1 < scopes.len() {
        let Some(sources) = scopes.get(index) else {
          break;
        };
        let Some(callback) = scopes.get(index + 1) else {
          break;
        };
        if sources.kind == TrackingScopeKind::WatchSources
          && callback.kind == TrackingScopeKind::WatchCallback
          && sources.reads.is_empty()
          && !callback.reads.is_empty()
        {
          findings.push(callback.span.clone());
        }
        index += 1;
      }
    }
    for span in findings {
      context.report(
        self.meta(),
        span,
        "reactive reads in a `watch` callback are not tracked for invalidation".into(),
        Some(
          "List dependencies in the `watch` source argument; the callback is a side-effect sink."
            .into(),
        ),
      );
    }
  }
}

static P_WATCH_CALLBACK_TRACKING: WatchCallbackTrackingRule = WatchCallbackTrackingRule;

struct DestructureSourceRule {
  meta: &'static RuleMeta,
  source: &'static str,
  message: &'static str,
  help: &'static str,
  pinia_store: bool,
}

impl Rule for DestructureSourceRule {
  fn meta(&self) -> &'static RuleMeta {
    self.meta
  }

  fn fact_kinds(&self) -> FactKinds {
    FactKinds::SCRIPT_DESTRUCTURE
  }

  fn run_on(&self, fact: FactRef<'_>, context: &mut RuleContext<'_>) {
    let FactRef::ScriptDestructure { destructure, .. } = fact else {
      return;
    };
    let matched = if self.pinia_store {
      let name = destructure.source_call.as_str();
      name.starts_with("use") && name.ends_with("Store")
    } else {
      destructure.source_call == self.source
    };
    if !matched {
      return;
    }
    context.report(self.meta(), destructure.span.clone(), self.message.into(), Some(self.help.into()));
  }
}

macro_rules! destructure_rule {
  ($static_name:ident, $id:literal, $doc:literal, $source:literal, $message:literal, $help:literal, $pinia:expr) => {
    static $static_name: DestructureSourceRule = DestructureSourceRule {
      meta: &RuleMeta {
        id: $id,
        category: "reactivity",
        default_severity: Severity::Warning,
        confidence: Confidence::High,
        documentation: $doc,
      },
      source: $source,
      message: $message,
      help: $help,
      pinia_store: $pinia,
    };
  };
}

destructure_rule!(
  I_REACTIVE_DESTRUCTURE,
  "vue-vet/reactivity/no-reactive-destructure",
  "rules/reactivity/no-reactive-destructure",
  "reactive",
  "destructuring `reactive()` loses reactivity for the pulled fields",
  "Keep the reactive object, or use `toRefs` / `toRef`.",
  false
);
destructure_rule!(
  I_SHALLOW_REACTIVE_DESTRUCTURE,
  "vue-vet/reactivity/no-shallow-reactive-destructure",
  "rules/reactivity/no-shallow-reactive-destructure",
  "shallowReactive",
  "destructuring `shallowReactive()` loses reactivity for the pulled fields",
  "Keep the shallowReactive object, or use `toRefs` / `toRef`.",
  false
);
destructure_rule!(
  I_PREFER_STORE_TO_REFS,
  "vue-vet/reactivity/prefer-store-to-refs",
  "rules/reactivity/prefer-store-to-refs",
  "",
  "destructuring a Pinia store loses reactivity for state fields",
  "Use `storeToRefs(store)` for state/getters, and keep actions on the store object.",
  true
);
destructure_rule!(
  I_ROUTE_DESTRUCTURE,
  "vue-vet/reactivity/no-route-destructure",
  "rules/reactivity/no-route-destructure",
  "useRoute",
  "destructuring `useRoute()` loses reactivity",
  "Keep the route object or read `route.params` / `route.query` through it.",
  false
);
destructure_rule!(
  I_ROUTER_DESTRUCTURE,
  "vue-vet/reactivity/no-router-destructure",
  "rules/reactivity/no-router-destructure",
  "useRouter",
  "destructuring `useRouter()` is usually unnecessary and can hide API misuse",
  "Keep the router instance and call methods on it.",
  false
);

struct RefOperandRule {
  meta: &'static RuleMeta,
  kinds: &'static [ReactiveBindingKind],
  label: &'static str,
}

impl Rule for RefOperandRule {
  fn meta(&self) -> &'static RuleMeta {
    self.meta
  }

  fn fact_kinds(&self) -> FactKinds {
    FactKinds::SCRIPT_OPERAND
  }

  fn run_on(&self, fact: FactRef<'_>, context: &mut RuleContext<'_>) {
    let FactRef::ScriptOperand { block_kind, operand } = fact else {
      return;
    };
    let Some(block) = context.script().blocks.iter().find(|block| block.kind == block_kind) else {
      return;
    };
    let Some(binding) = block
      .reactivity_graph
      .bindings
      .iter()
      .find(|binding| binding.name == operand.name)
    else {
      return;
    };
    if !self.kinds.contains(&binding.kind) {
      return;
    }
    context.report(
      self.meta(),
      operand.span.clone(),
      format!(
        "`{}` is a {} object used as an operand; unwrap with `.value` (or `toValue`)",
        operand.name, self.label
      ),
      Some(format!(
        "Use `{}.value` (or `toValue({})`) when reading the inner value.",
        operand.name, operand.name
      )),
    );
  }
}

macro_rules! ref_operand_rule {
  ($static_name:ident, $id:literal, $doc:literal, $label:literal, [$($kind:ident),+]) => {
    static $static_name: RefOperandRule = RefOperandRule {
      meta: &RuleMeta {
        id: $id,
        category: "reactivity",
        default_severity: Severity::Warning,
        confidence: Confidence::High,
        documentation: $doc,
      },
      kinds: &[$(ReactiveBindingKind::$kind),+],
      label: $label,
    };
  };
}

ref_operand_rule!(
  I_REF_AS_OPERAND,
  "vue-vet/reactivity/no-ref-as-operand",
  "rules/reactivity/no-ref-as-operand",
  "ref",
  [Ref, ShallowRef, CustomRef, ToRef, TemplateRef]
);
ref_operand_rule!(
  I_MODEL_REF_AS_OPERAND,
  "vue-vet/reactivity/no-model-ref-as-operand",
  "rules/reactivity/no-model-ref-as-operand",
  "defineModel ref",
  [ModelRef]
);
ref_operand_rule!(
  I_COMPUTED_AS_OPERAND,
  "vue-vet/reactivity/no-computed-as-operand",
  "rules/reactivity/no-computed-as-operand",
  "computed ref",
  [Computed]
);

struct ReadonlyMutationRule;

impl Rule for ReadonlyMutationRule {
  fn meta(&self) -> &'static RuleMeta {
    &RuleMeta {
      id: "vue-vet/reactivity/no-readonly-mutation",
      category: "reactivity",
      default_severity: Severity::Warning,
      confidence: Confidence::High,
      documentation: "rules/reactivity/no-readonly-mutation",
    }
  }

  fn fact_kinds(&self) -> FactKinds {
    FactKinds::SCRIPT_MEMBER_WRITE
  }

  fn run_on(&self, fact: FactRef<'_>, context: &mut RuleContext<'_>) {
    let FactRef::ScriptMemberWrite { block_kind, write } = fact else {
      return;
    };
    let Some(block) = context.script().blocks.iter().find(|block| block.kind == block_kind) else {
      return;
    };
    let Some(binding) =
      block.reactivity_graph.bindings.iter().find(|binding| binding.name == write.object)
    else {
      return;
    };
    if !is_readonly_kind(binding.kind) {
      return;
    }
    context.report(
      self.meta(),
      write.span.clone(),
      format!("`{}` is readonly and should not be mutated", write.object),
      Some("Mutate the source reactive state instead of a readonly projection.".into()),
    );
  }
}

static I_READONLY_MUTATION: ReadonlyMutationRule = ReadonlyMutationRule;

// Reserved: register when top-level vs nested template-ref reads are distinguishable.
#[allow(dead_code)]
struct TemplateRefSetupReadRule;
#[allow(dead_code)]
static I_TEMPLATE_REF_SETUP_READ: TemplateRefSetupReadRule = TemplateRefSetupReadRule;
"""
  )

  all_statics = (
    b_statics
    + a_statics
    + p_statics
    + [
      "P_WATCH_CALLBACK_TRACKING",
      "I_REACTIVE_DESTRUCTURE",
      "I_SHALLOW_REACTIVE_DESTRUCTURE",
      "I_PREFER_STORE_TO_REFS",
      "I_ROUTE_DESTRUCTURE",
      "I_ROUTER_DESTRUCTURE",
      "I_REF_AS_OPERAND",
      "I_MODEL_REF_AS_OPERAND",
      "I_COMPUTED_AS_OPERAND",
      "I_READONLY_MUTATION",
    ]
  )

  parts.append("#[must_use]\npub fn matrix_rules() -> Vec<&'static dyn Rule> {\n  vec![")
  for name in all_statics:
    parts.append(f"    &{name},")
  parts.append("  ]\n}\n")

  OUT.parent.mkdir(parents=True, exist_ok=True)
  OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
  print(f"wrote {OUT} ({len(all_statics)} rules)")


if __name__ == "__main__":
  main()
